EVT_PAUSE = 100
EVT_DESTROY = 101
OS_LINUX = 201
OS_MAC = 202
OS_WINDOWS = 203
TITLE = "Final Hour"
SOUNDPREPEND = "data/"
DEFAULT_HOST = "localhost"
DEFAULT_PORT = 13000
SERVER_SOUNDS_URL = "https://final-hour.net/sounds/"
TIMEOUT = 5000
SETTINGS_KEY = b"mquBJ6q6YIMKxvf8PB880i-bL-DPNv3GPs63FZuD1yQ="
CHANNEL_MISC = 0
CHANNEL_CHAT = 1
CHANNEL_MAP = 4
CHANNEL_PING = 5
CHANNEL_MENUS = 6
CHANNEL_WEAPONS = 7
CHANNEL_SERVER_SOUNDS = 8
CHANNEL_VOICECHAT = 20
CHANNEL_MEGAPHONE = 30
CHANNEL_MUSICBOT = 22
SOUNDSPREPEND="/data/"

# 🔢 Version for server compatibility check
CLIENT_VERSION = "0.33.6"
